### ISSUE TITLE
Question regarding the results

### ISSUE THREAD

**Issue by gstaryu** [poseidonchan/TAPE#17]
First of all, thank you very much for your work.
I have a question: I noticed that the pred results of several datasets are provided in the attachment `SuppData_TAPE\TAPE\real\`. I plotted box plots of CCC for `monaco_pred.csv` and `sdy67_pred.csv`, but I found a significant difference compared to the results in Figure 2-d of the paper. Should I refer to the results in the attachment `SuppData_TAPE\TAPE\real\` or those in Figure 2-d of the paper? Perhaps I have misunderstood your intent?

As shown in the figure below: the top image displays the results for the monaco and sdy67 datasets from your attachment `SuppData_TAPE\TAPE\real\`, while the bottom image shows the results from Figure 2-d of the paper.
![output](https://github.com/user-attachments/assets/6f0d716a-b083-4185-9dd4-be44ba5cb3b5)

![paper_res](https://github.com/user-attachments/assets/dd48e685-3f9a-4419-a594-bd6ac84d6411)

I am quite confused and may have misunderstood the meaning of the files in your attachment. Could you please clarify? Thank you.

**Comment by poseidonchan** [comment]
Thanks for reaching out!

I am sorry that I forget about the details since it has been a long time. But you can always reproduce the results with the notebook (https://github.com/poseidonchan/TAPE/blob/main/Experiments/TAPE_realbulk.ipynb) and corresponding data.
Moreover, please bear the performance differences since different random seeds may affect the performance significantly.

Yanshuo
