### ISSUE TITLE
unable to get expected results

### ISSUE THREAD

**Issue by robinredX** [poseidonchan/TAPE#4]
Hi, thanks for the nice tool.
I was trying TAPE on SDY67 using  Tape. I took following steps:

1. As used in TAPE, I downloaded simulated PBMC data from Scaden (https://figshare.com/articles/dataset/PBMC_training_data/8052221).
2. I seperated the h5ad file into pbmc_data_sim.h5ad (which includes four simulated datasets) and a txt file which includes bulk dataset (bulk.txt).
3. I chose following parameters: datatype = "counts" as suggested in the readme file because the simulated dataset is from 10x, mode = "overall", adaptive = True and batch size=128. I chose 20 epochs based on the formula in readme.

I am using following parameters in Deconvolution(). 

```
Deconvolution("pbmc_data_sim.h5ad",  "bulk.txt", sep='\t', datatype='counts', genelenfile=None, mode='overall', adaptive=True,
                           save_model_name="tape_sdy67",
                           batch_size=128, epochs=20)
```
My results are as follows:

```
Monocytes
CCC: 0.14
r: 0.43
RMSE: 0.07
-----
CD4Tcells
CCC: nan
r: nan
RMSE: 0.33
-----
Bcells
CCC: nan
r: nan
RMSE: 0.05
-----
NK
CCC: 0.08
r: 0.66
RMSE: 0.07
-----
CD8Tcells
CCC: 0.02
r: 0.35
RMSE: 0.23
-----
Over all celltypes
CCC: 0.37
r: 0.4
RMSE: 0.19
```
I don't know what I am doing wrong. Is there some step that I am missing?

Thanks. 
robin.

**Comment by poseidonchan** [comment]
Hi, Robin:

Thanks for trying TAPE and pointing out the problem. To solve your problem, I quickly tested it. I am not sure about the concrete bug, I propose some possible reasons and I put a reproducible notebook for your test.

I checked the code and noticed that the network structure in https://github.com/poseidonchan/TAPE/blob/main/TAPE/model.py has an extra CELU() function. I will fix it in further version.

On the other hand, I notice that you train it with four simulation datasets and 20 epochs. But in our paper, we only use data8k for training. Because, in my practice, I find that using data8k only is better.

Further issues may be related to the variance cutoff choice.

In this repository, I store the original file when I test the real bulk performance of TAPE (https://github.com/poseidonchan/TAPE/blob/main/Experiments/TAPE_realbulk.ipynb). You can check it. For your information, I also tested the performance in the following file a few minutes ago. (Sorry for the inconvenience, I will also email you the original notebook file.)  You can run the code I attached to test it.
[TAPE_sdy67_response.pdf](https://github.com/poseidonchan/TAPE/files/9389642/TAPE_sdy67_response.pdf)

In my test, the overall ccc is around 0.7 and the L1 error is around 0.065.

Though the manuscript is still under review, I must apologize for the immature public version and the inconvenience, I will fix it as soon as possible.

Good Evening,
Yanshuo

**Comment by robinredX** [comment]
Thank you for this quick response and sending the notebook.
robin.

**Comment by fanying2015** [comment]
Thank you for sharing the script and the input pbmc_data.h5ad. I was able to reproduce the performance with the script shared. However, when I extracted the input training and testing data extracted from pbmc_data.h5ad, and re-ran it with the most-updated scTAPE, I was not able to reproduce the good performance.

Below is the script:
bulkdata = "data/sdy67_pbmc_T.txt"
SignatureMatrix, CellFractionPrediction = \
    Deconvolution(data8k, 
                  bulkdata, 
                  datatype='counts',
                  mode='overall', 
                  adaptive=True, 
                  genelenfile='data/GeneLength.txt',
                  variance_threshold=0.98,
                  save_model_name=None,
                  batch_size=128, epochs=128, seed=1)

Here's the output I got:
Overall ccc score is 0.2681609832003653
Overall L1 error is 0.09960681947553503
Monocytes's ccc score is 0.016779699438862313 l1 error is 0.16584189928137005
Unknown's ccc score is 0.018452949504123843 l1 error is 0.04238455120367027
CD4Tcells's ccc score is 0.01811648028004676 l1 error is 0.11177192915514465
Bcells's ccc score is 0.012134334312653563 l1 error is 0.03713114535164252
NK's ccc score is 0.0049701328499787535 l1 error is 0.05943935639606579
CD8Tcells's ccc score is 0.007200250637215528 l1 error is 0.1810720354653168
